- releases/stg/libero-editor.yaml
Added an initial config file for deploying Libero Editor to the staging environment.
> feat: add initial staging environment config for libero editor

- releases/stg/libero-editor.yaml
Fixed wrong path for chart, and wrong container for article-store
> fix: minor errors in libero-editor staging config

- releases/prod/basex-validator.yaml
- releases/stg/basex-validator.yaml
Added configurations for the basex-validator service for both staging and production
environments.
> feat: support for basex-validator service

- releases/adm/prometheus-operator.yaml
- releases/adm/sciencebeam-alert-rules.yaml
related to https://github.com/elifesciences/sciencebeam-issues/issues/68
> added sciencebeam rules

- releases/prod/sciencebeam-texture.yaml
part of https://github.com/elifesciences/sciencebeam-issues/issues/97
> increased grobid memory limits

- system/infra/external-dns.yaml
Incorporating changes to the chart values
> release(external-dns): update the external DNS chart to the latest version

- .github/workflows/e2e.yaml
- system/crossplane/namespace.yaml
- system/crossplane/release.yaml
- system/crossplane/source.yaml
> Add Crossplane

- .github/workflows/epp_previews.yaml
- deployments/epp/previews/README
- kustomizations/apps/epp/deployment.yaml
- kustomizations/apps/epp/ingress.yaml
- kustomizations/apps/epp/kustomization.yaml
- kustomizations/apps/epp/namespace.yaml
- kustomizations/apps/epp/preview_template.yaml
- kustomizations/apps/epp/service.yaml
- scripts/merge_epp_preview_envs_with_open_prs.sh
Design a script that queries open PRs and generates flux kustomizations for an EPP env
> EPP preview environments

- deployments/epp/ingress.yaml
Closes https://github.com/elifesciences/enhanced-preprints-server/issues/6
> create a new ingress endpoint that integrates the client, the server/api and IIIF together

- system/crossplane/namespace.yaml
- system/crossplane/release.yaml
- system/crossplane/source.yaml
Revert "deploy(crossplane): remove unused services to create capacity"
This reverts commit 6af79409c31cfa803c6a6ba0c493ce66e95496a7.
> deploy(crossplane): reinstall crossplane

- deployments/podinfo/imagerepository.yaml
- deployments/podinfo/namespace.yaml
- deployments/podinfo/stg/automations/policy.yaml
- deployments/podinfo/stg/automations/updateautomation.yaml
- deployments/podinfo/stg/canary.yaml
- deployments/podinfo/stg/deployment.yaml
- deployments/podinfo/stg/ingress.yaml
Revert "deploy(podinfo): remove podinfo to free capacity"
This reverts commit 5e95b3e0aaf7acde06ea0912fd5b06ed6d1e637c.
> deploy(podinfo): reinstall podinfo

- system/monitoring/service-monitors/cadvisor.yaml
- system/monitoring/service-monitors/kubelet.yaml
relates to https://github.com/elifesciences/issues/issues/8171
> deploy(system/monitoring/service-monitors): add kubelet and cadvisor service monitors

- system/monitoring/podlogs/podlogs.yaml
relates to https://github.com/elifesciences/issues/issues/8171
> deploy(system/monitoring/podlogs): add PodLogs for all namespaces

- system/monitoring/grafana-cloud/integrations/agent-event-handler.yaml
- system/monitoring/grafana-cloud/integrations/node-exporter.yaml
relates to https://github.com/elifesciences/issues/issues/8171
> deploy(system/monitoring/grafana-cloud): add integrations

- eks/kustomization.yaml
related to https://github.com/elifesciences/issues/issues/8193
> fix(eks/aws-ebs-csi-driver): add CSI driver to eks kustomization

- eks/addons/kube-proxy.yaml
- system/autoscaler/release.yaml
- system/kube-system/descheduler/release.yaml
relates to https://github.com/elifesciences/issues/issues/8196
> deploy(system/eks-addons,system/autoscaler,system/descheduler): upgrade eks and kubernetes addons to versions for EKS 1.23

- .github/workflows/e2e.yaml
fixes https://github.com/elifesciences/issues/issues/8217
> Make the CI use the version of flux indicated in the prod cluster manifest

- tests/resources_to_test.txt
https://github.com/elifesciences/issues/issues/9065
> fix external-dns tests

- system/template-controller/release.yaml
- system/template-controller/source.yaml
> deploy(template-controller): migrate to new template controller helm chart delivered via oci elifesciences/issues#9153

- crds/ack-controllers/common/services.k8s.aws_adoptedresources.yaml
- crds/ack-controllers/common/services.k8s.aws_fieldexports.yaml
- crds/ack-controllers/common/update.sh
- crds/update_all.sh
> deploy(crds/ack-controllers/common): manage and update the shared ACK controller CRDs 

- system/clusterclasses/base/kustomization.yaml
- system/nidhogg/kustomization.yaml
- system/nidhogg/namespace.yaml
- system/nidhogg/release.yaml
- system/nidhogg/source.yaml
- system/spegel/kustomization.yaml
- system/spegel/namespace.yaml
- system/spegel/release.yaml
- system/spegel/source.yaml
- tests/resources_to_test.txt
https://github.com/elifesciences/issues/issues/9192
> Spegel deployment elifesciences/issues#9192

- crds/external-secrets/external-secrets.crds.yaml
- system/clusterclasses/eks/secret-store/secrets-manager.yaml
- system/clusterclasses/kind-test/secret-store/fake-secret-store.yaml
- system/external-secrets/external-secrets/release.yaml
- system/infra/external-secrets/oauth2-github.yaml
- system/vector/secrets/gcp-data-hub-project-log-shipping.yaml
- system/victoriametrics/secrets/alerts-urls.yaml
Reverts elifesciences/elife-flux-test#1800
> Revert "chore(deps): update helm release external-secrets to v0.16.0"

- crds/external-secrets/external-secrets.crds.yaml
- system/clusterclasses/eks/secret-store/secrets-manager.yaml
- system/clusterclasses/kind-test/secret-store/fake-secret-store.yaml
- system/external-secrets/external-secrets/release.yaml
- system/infra/external-secrets/oauth2-github.yaml
- system/vector/secrets/gcp-data-hub-project-log-shipping.yaml
- system/victoriametrics/secrets/alerts-urls.yaml
Reapply the external secrets upgrade, we will find a way
> Revert "Revert "chore(deps): update helm release external-secrets to v0.16.0""
